name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version to use

      - name: Install dependencies
        run: npm install  # Installs your app dependencies

     # - name: Run tests
     #   run: npm test  # Run your test scripts (optional if you have tests)

      - name: Build and Deploy
        run: npm run build  # This could be your build script if you have one, otherwise just use "npm start"
