name: Deploying Docker Image to Heroku

on:
  push:
    branches: 
      [ "main" ]
  pull_request:
    branches: 
      [ "main" ]

jobs:
  # Job 1: Build the Docker image and run tests
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/image-search-app-v1.0.0:latest

      - name: Run tests (optional)
        run: |
          # Here you can add your testing scripts/commands, for example:
          # npm test
          echo "Running tests... (Replace with actual test commands)"

  # Job 2: Deploy to Heroku
  deploying_to_Heroku:
    needs: build_and_test  # This job depends on the success of the build_and_test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Heroku
        uses: akshnz/heroku-deploy@v1.0.0
        with:
          api_key: ${{ secrets.HEROKU_API_KEY }}  # Heroku API Key from your Heroku account

      - name: Deploy to Heroku
      - uses: ./.github/workflows/docker-image.yml  # Reference the reusable workflow 
      - run: |
          heroku container:login
          heroku container:push web --app image-search-app
          heroku container:release web --app image-search-app
  
